# Generated by Django 4.2.7 on 2023-11-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_project_cost_project_cost_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_partners',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(related_name='related_projects', to='projectmanager.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Development', 'Development')], default='Ongoing', max_length=15),
            preserve_default=False,
        ),
    ]
