# Generated by Django 4.2.7 on 2023-11-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_remove_project_partners_project_partner_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='has_partners',
        ),
    ]
