# Generated by Django 4.2.7 on 2023-11-23 20:31

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_remove_project_has_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='survey_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True),
        ),
    ]
